manage smcroute service for multicast forwarding

diff --git a/script/_smcroute b/script/_smcroute
--- a/script/_smcroute
+++ b/script/_smcroute
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 #
-#  Copyright (c) 2017, The OpenThread Authors.
+#  Copyright (c) 2020, The OpenThread Authors.
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -26,10 +26,40 @@
 #  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #  POSSIBILITY OF SUCH DAMAGE.
 #
+#   Description:
+#       This script manipulates smcroute configuration.
+#
 
-# shellcheck disable=SC2034
-NAT64=1
-DNS64=1
-DHCPV6_PD=0
-NETWORK_MANAGER=0
-SMCROUTE=1
+smcroute_uninstall()
+{
+    if command -v systemctl; then
+        sudo systemctl stop smcroute || true
+    fi
+
+    sudo killall smcrouted || true
+
+    test -d "$BUILD_DIR"/smcroute || return 0
+
+    (cd "$BUILD_DIR"/smcroute \
+        && (test ! -f config.status || sudo make uninstall))
+}
+
+smcroute_install()
+{
+    test -d "$BUILD_DIR"/smcroute || (cd "$BUILD_DIR" \
+        && git clone -b ip6_mf --depth 1 https://github.com/librasungirl/smcroute.git) || die 'Failed to download source code of SMCRoute!'
+
+    (
+        cd "$BUILD_DIR"/smcroute || return 1
+        test -f configure || ./autogen.sh
+        test -f config.status || ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
+        make
+        sudo make install
+
+        if command -v systemctl; then
+            sudo systemctl enable smcroute
+            sudo systemctl restart smcroute
+        fi
+
+    )
+}
